Object.assign(
	exports,
	require('./types/index.js'),
	require('./default-generator-options/index.js'),
	require('./generator/index.js'),
	require('./is-weak-operator/index.js'),
	require('./precedences/index.js'),
	require('./walker/index.js'),
	require('./comment/index.js'),
	require('./print/index.js'),
	require('./analyze/index.js')
);
